# This is a GH action that runs whenever you push. See the Actions tab on the GH
# repo to see the results.
name: Build and Test

on:
  push:
    branches:
      - "**"

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.1

      - name: Add /usr/local/go/bin to PATH
        run: echo "/usr/local/go/bin" >> $GITHUB_PATH

      - name: Build and Test
        run: |
          set -e -x -v -u -o pipefail
          bash .github/scripts/build-and-test.sh